# AI-assisted development — firmware, HA automation, config generator and docs were created with AI (LLM) help, reviewed and tested by the author. Provided as-is, without warranty; verify on your own hardware, don't use for safety-critical applications.
"""The browser fixtures must match the server they stand in for.

The browser suite runs against recorded fixtures instead of a live backend, which
makes it fast and deterministic — and makes a stale recording invisible: the tests
keep passing against *yesterday's* ``/api/meta`` while the real descriptors,
templates or caps have moved on. That actually happened (the Spotify template's item
names were renamed and the browser test still asserted the old ones, because the
fixture predated the rename), so the snapshot is now a gate:

    .venv/bin/python scripts/record_frontend_fixtures.py   # re-record
    git diff tests/fixtures/                              # review what moved
"""

from __future__ import annotations

import json
from pathlib import Path

from micropad.constants import AI_NOTICE

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURES = REPO_ROOT / "tests" / "fixtures"


def _load(name: str) -> dict:
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


def test_recorded_meta_fixture_matches_the_live_api_meta(client):
    """``frontend_meta.json`` is a copy of ``/api/meta``; a copy may not drift."""
    recorded = _load("frontend_meta.json")
    assert recorded.pop("_ai_assisted_notice") == AI_NOTICE
    assert recorded == client.get("/api/meta").get_json(), (
        "tests/fixtures/frontend_meta.json is out of date - re-record it with "
        "'.venv/bin/python scripts/record_frontend_fixtures.py' and review the diff"
    )


def test_recorded_meta_fixture_carries_the_fields_the_browser_suite_uses():
    """The fixture is only useful if it has the keys the editor reads.

    A recording that silently lost a block would make the browser suite test a
    degenerate API, so the shape is pinned here as well as the values.
    """
    recorded = _load("frontend_meta.json")
    for key in (
        "actions", "automation_id", "caps", "controls", "control_meta",
        "default_keymap", "gestures", "gesture_meta", "home_page_id", "item_types",
        "item_type_meta", "key_ids", "limits", "mqtt_contract_version", "templates",
    ):
        assert key in recorded, f"frontend_meta.json is missing {key!r}"


def test_panel_fixture_is_the_core_model_for_the_config_fixture_page():
    """``frontend_panel.json`` must describe the page the config fixture starts with.

    The prim list itself is regenerated by the recording script (and covered by the
    golden payloads); what this pins is that the recording still belongs to the
    fixture page, so a re-recorded config cannot leave the preview drawing a page
    that no longer exists.
    """
    config = _load("frontend_config.json")
    panel = _load("frontend_panel.json")
    assert panel["page_id"] == config["pages"][0]["page_id"]
    assert panel["response"]["prims"], "a recorded panel without prims proves nothing"
